name: auto cancellation running job
on:
   push:
     branches:
       - master  

jobs:
  canceljob:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "build_documentation.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

