name: auto cancellation running job
on:
   push:
     branches:
       - master  

jobs:
  canceljob:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }

