 on:
   push:
     branches:
       - master  

 env:
   DOC_SUBDIR: latest

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - name:  checkout source branch 
       uses: actions/checkout@v1   
       with:
         ref: master     
     - name: build documentation website in build/html/
       uses: ammaraskar/sphinx-action@master
       with:
         docs-folder: "."
     - name: build documentation pdf in build/latex/
       uses: ammaraskar/sphinx-action@master
       with:
         pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
         build-command: "make latexpdf"
         docs-folder: "."    
     - name: Add and commit build documentation to gh-pages branch          
       run: |
         # clone gh-pages branch into 
         git clone "github.com/$GITHUB_REPOSITORY.git" --branch gh-pages --single-branch gh-pages
         rsync -av --delete  build/html/ gh-pages/$DOC_SUBDIR/   
         cp build/latex/*.pdf gh-pages/$DOC_SUBDIR/                   
         cd gh-pages
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add .
         git commit -m "Update documentation" -a || true
         # The above command will fail if no changes were present, so we ignore that.
     - name: Push changes in gh-pages directory to gh-pages branch
       uses: ad-m/github-push-action@master
       with:
         branch: gh-pages
         directory: gh-pages
         github_token: ${{ secrets.GITHUB_TOKEN }}
